### ISSUE TITLE
`get_bgp_neighbors_detail`: KeyError: u'advertised_prefix_count'

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-eos#122]
### Description of Issue/Question

Unable to execute `get_bgp_neighbors_detail`.

### napalm-eos version
(Paste verbatim output from `pip freeze | grep napalm-eos` between quotes below)

```
0.5.2
```

### eOS version
(Paste verbatim output from `show version | json` between quotes below)

```
any
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
>>> e.get_bgp_neighbors_detail()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/napalm_eos/eos.py", line 1390, in get_bgp_neighbors_detail
    v4_peer_info = _parse_per_peer_bgp_detail(raw_output[0]['output'])
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/napalm_eos/eos.py", line 1306, in _parse_per_peer_bgp_detail
    item[key] = napalm_base.helpers.convert(int, item[key], 0)
KeyError: u'advertised_prefix_count
```

**Comment by mirceaulinic** [comment]
Not a bug - this was actually solved in https://github.com/napalm-automation/napalm-eos/commit/b98bd1a984cc064acb879bd2887a144c4b04766d
