### ISSUE TITLE
LLDP chassisId is converted to a MAC address for non-MAC address chassisId values

### ISSUE THREAD

**Issue by colinmcintosh** [napalm-automation/napalm-eos#138]
### Description of Issue/Question

napalm-eos get_lldp_neighbor_detail() tries to convert all chassisId values to a MAC address format but per [rfc2992](https://tools.ietf.org/html/rfc2922) (under the section for PtopoChassisIdType) chassisId is not required to be a MAC address.

### napalm-eos version

```
napalm-eos==0.5.3
```

### eOS version
```
4.15.5
```

### Steps to Reproduce the Issue

Run get_lldp_neighbors_detail() on a switch receiving a chassisId TLV that is not a MAC address.

### Error Traceback

```
Traceback (most recent call last):
  File "napalm_example.py", line 28, in <module>
    main()
  File "napalm_example.py", line 19, in main
    print(json.dumps(device.get_lldp_neighbors_detail(), indent=4))
  File "/home/user/Test/napalm/napalm-eos/napalm_eos/eos.py", line 538, in get_lldp_neighbors_detail
    neighbor.get('chassisId', u'')),
  File "/home/user/Test/napalm/env/local/lib/python2.7/site-packages/napalm_base-0.23.0-py2.7.egg/napalm_base/helpers.py", line 219, in mac
    return py23_compat.text_type(EUI(raw, dialect=_MACFormat))
  File "/home/user/Test/napalm/env/local/lib/python2.7/site-packages/netaddr-0.7.19-py2.7.egg/netaddr/eui/__init__.py", line 387, in __init__
    self.value = addr
  File "/home/user/Test/napalm/env/local/lib/python2.7/site-packages/netaddr-0.7.19-py2.7.egg/netaddr/eui/__init__.py", line 437, in _set_value
    % value)
netaddr.core.AddrFormatError: failed to detect EUI version: u'"AAAA-BBBB"'
```

**Comment by dbarrosop** [comment]
Associated PR has been merged. Closing issue. Feel free to reopen if you think there is something to be done.
