### ISSUE TITLE
Untested release 0.4.0 blown some getters

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-eos#68]
### Description of Issue/Question

Including `get_interfaces`, `get_interfaces_ip` or `get_bgp_neighbors_detail`.
### napalm-eos version

(Paste verbatim output from `pip freeze | grep napalm-eos` between quotes below)

```
napalm-eos==0.4.0
```
### eOS version

(Paste verbatim output from `show version | json` between quotes below)

```
any
```
### Error Traceback

(Paste the complete traceback of the exception between quotes below)

```
>>> e.get_interfaces()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/state/home/mircea/napalm/local/lib/python2.7/site-packages/napalm_eos/eos.py", line 249, in get_interfaces
    values.pop('physicalAddress', u'')
  File "/state/home/mircea/napalm/local/lib/python2.7/site-packages/napalm_base/helpers.py", line 217, in mac
    return unicode(EUI(raw, dialect=_MACFormat))
  File "/state/home/mircea/napalm/local/lib/python2.7/site-packages/netaddr/eui/__init__.py", line 387, in __init__
    self.value = addr
  File "/state/home/mircea/napalm/local/lib/python2.7/site-packages/netaddr/eui/__init__.py", line 437, in _set_value
    % value)
netaddr.core.AddrFormatError: failed to detect EUI version: u''
>>>
```

**Comment by dbarrosop** [comment]
Could you add a test case to #69 with the output that device is giving you? This is the perfect use case : )
