### ISSUE TITLE
get_environment() should not generate an exception on vEOS

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-eos#90]
Arista vEOS

```
Traceback (most recent call last):
  File "./test_napalm_get.py", line 103, in <module>
    wrapper_func(conn, napalm_method, banner=banner)
  File "./test_napalm_get.py", line 14, in wrapper_func
    pprint(my_method())
  File "/home/kbyers/applied_python/local/lib/python2.7/site-packages/napalm_eos/eos.py", line 458, in get_environment
    fans_output, temp_output, power_output = self.device.run_commands(command)
  File "/home/kbyers/applied_python/local/lib/python2.7/site-packages/pyeapi/client.py", line 672, in run_commands
    response = self._connection.execute(commands, encoding)
  File "/home/kbyers/applied_python/local/lib/python2.7/site-packages/pyeapi/eapilib.py", line 475, in execute
    response = self.send(request)
  File "/home/kbyers/applied_python/local/lib/python2.7/site-packages/pyeapi/eapilib.py", line 396, in send
    raise CommandError(code, msg, command_error=err, output=out)
pyeapi.eapilib.CommandError: Error [1000]: CLI command 4 of 4 'show environment power' failed: could not run command [There seem to be no power supplies connected.]
```

**Comment by mirceaulinic** [comment]
Not sure if this was introduced by https://github.com/napalm-automation/napalm-eos/pull/79 at all. Anyway, this should not happen.
I would just fill with default values the `power` section for vEOS (I think also `fans`, `temp` - not sure what else).
